

version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
       MYSQL_ROOT_PASSWORD: 1542
    ports:
      - 3305:3306
  database:
    image: database
    container_name: db_backend
    ports:
      - 8080:80  




    restart: unless-stopped
