

version: "3.9"
services:
  mysql_service:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1542
    ports:
      - 3305:3306
  database_service:
    build:
      context: ./dataBase
    ports:
      - 8080:80  

  front_service:
    build:
      context: ./Angular/frontend
    ports:
      - 8081:80 

  backend_service:
    build:
      context: ./backEnd
    ports:
      - 8083:80 

    restart: unless-stopped
