

version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1542
      MYSQL_DATABASE: sys
      MYSQL_USER: root
    ports:
      - 3305:3306
  database:
    image: dbservice
    container_name: dbservice
    ports:
      - 8080:80  

  front:
    image: frontend
    container_name: frontend
    ports:
      - 8081:80 




    restart: unless-stopped
